@startuml gateway_ack
title Sơ đồ quá trình xử lý gói tin có Header: PERIOD_SS tại Gateway

start
    :Lấy gói tin thô từ buffer nhận;

    if (Header == PERIOD_SS) then (Yes)
        if (Phân giải) then (Success)
            note left
                Các loại cảm biến
                - Nhiệt độ
                - Độ ẩm
                - Ánh sáng
            end note
            :Lấy địa chỉ nguồn của gói tin;
            :Lấy giá trị của cảm biến;
            :Cập nhật các giá trị 
            cảm biến của Node 
            lên Server;
        else (Fail)
            :Hủy bỏ gói tin;
        endif
    else (No)
        :Hủy bỏ gói tin;
    endif
stop
@enduml
