@startuml gateway_ack
title Sơ đồ quá trình xử lý gói tin có Header: ACK_STT tại Gateway

start
    :Đặt bộ đếm giờ cho gói tin ACK;
    :Lấy gói tin thô từ buffer nhận;

    if (Header == ACK_STT) then (Yes)
        if (Phân giải gói tin) then (Success)
            :Lấy dữ liệu Address và
            trường Data của gói tin;
            :Gửi giá trị trạng thái 
            của Node lên Server;
            :Đặt lại bộ đếm giờ;
        else (Fail)
            :Loại bỏ gói tin;
        endif
    else (No)
        :Loại bỏ gói tin;
    endif
stop
@enduml