@startuml gateway_ack
title Sơ đồ quá trình xử lý gói tin có Header: PERIOD_SS tại Gateway

start
    :Pop gói tin từ buffer;
    :Giải tuần tự gói tin để kiểm tra Header;

    if (Header == PERIOD_SS) then (Yes)
        if (Lấy giá trị:
        - Địa chỉ
        - Nhiệt độ
        - Độ ẩm
        - Ánh sáng) then (Hợp lệ)
            :Publish lên server trạng thái mới
            của đèn với địa chỉ tương ứng;
        else (Không hợp lệ)
            :Xem là gói tin lỗi, hủy bỏ;
        endif
    else (Header không hợp lệ)
        :Xem là gói tin lỗi, hủy bỏ;
    endif
stop
@enduml
