@startuml node_process_ACK_STT
title Sơ đồ quá trình xử lý gói tin có Header: ACK_STT tại Node

start
    :Pop gói tin từ buffer;
    :Giải tuần tự gói tin để kiểm tra Header;

    if (Header == ACK_STT) then (Yes)
        :Lấy dữ liệu Address và trường Data của gói tin;
        if (Address == own_address) then (Yes)
            :Lấy giá trị Relay và PWM;
            :Xử lý lệnh điều khiển thông qua 2 tham số Relay và PWM;
        else (No)
            :Loại bỏ gói tin;
        endif
    else (Header không hợp lệ)
        :Loại bỏ gói tin;
    endif

stop
@enduml