@startuml gateway_server
title Sơ đồ quá trình xử lý gói tin từ Server tới Gateway

start
    :Lấy gói tin thô từ buffer nhận;
    :Phân giải gói tin;
    :Phân loại gói tin 
    dựa trên trường 
    Method;

    if (Lệnh điều khiển hợp lệ) then (Success)
        :Đặt Timer;
        :Gửi lệnh điều khiển;
        :Thực hiện "Cơ chế gửi lại gói tin";

        if (Nhận phản hồi) then (Yes)
            :Gửi trạng thái 
            hiện tại của Node 
            lên Server;
        else (No)
            :Do nothing;
        endif
    else (Fail)
        :Do nothing;
    endif
stop
@enduml

@startuml message_classify
title Cơ chế phân loại gói tin
start
    if (Method == setState) then (Yes)
        :Tạo ra gói tin 
        điều khiển Relay;
    elseif (Method == setPWM) then (Yes)
        :Tạo ra gói tin 
        điều khiển PWM;
    else (No)
        :Loại bỏ gói tin;
    endif
stop
@enduml

@startuml wait_and_retry
title Cơ chế gửi lại gói tin
start
    while (retry < MAX RETRY and No response) is (Yes)
        :Kiểm tra gói tin trong buffer;
        if (Timeout) then (Yes)
            :Tăng số lần thử;
            :Đặt lại Timer;
        else (No)
            :Do nothing;
        endif
    endwhile
stop
@enduml
